#+title: My notes, taken while writing the article


* Article thoughts

I want the article to be a narrative interwoven between theory such
that the narrative illustrates the theory.

I want the beginning of the article to hold a quote from Cory
Doctorow's Walkaway that says that the stories we tell come true.

“Look, there are as many walkaway philosophies as there are walkaways,
but mine is, 'the stories you tell come true.' If you believe everyone
is untrustworthy, you'll build that into your systems so that even the
best people have to act like the worst people to get anything done. If
you assume people are okay, you live a much happier life.”

I want the article to discuss the stories we tell ourselves, and to
put in quotes from powerful people to back those stories.

I want it to first discuss the operating principle from neo-liberal
capitalism that everyone is primarily self-interested and selfish, and
so we built a system on that.

“Look, there are as many walkaway philosophies as there are walkaways,
but mine is, 'the stories you tell come true.' If you believe everyone
is untrustworthy, you'll build that into your systems so that even the
best people have to act like the worst people to get anything done. If
you assume people are okay, you live a much happier life.”

Leviathan, Hobbes (page 78)

## What the hell is water?

>There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says “Morning, boys. How’s the water?” And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes “What the hell is water?”"
>
>*- [This Is Water: Some Thoughts, Delivered on a Significant Occasion,
>about Living a Compassionate Life, David Forster Wallace](https://fs.blog/david-foster-wallace-this-is-water/)*

Like water for fish, or air for humans, a story can surround you so completely that it disappears into significance. It becomes truth.


* Article outline

- Starts with a claim that one of the most important parts of our
  societies is the stories we tell another. Those stories get passed
  on orally, literally or just through the process of invisible
  osmosis that we refer to as culture. Culture is a boundary, it's the
  water we breathe. Bring in the "this is water" quote from David Forster-Wallace.

- Proceeds to take a couple of stories as examples and then criticizes
  them from within their constructs and compares them to alternative
  tellings of the same facts.

  Social darwinism being the first one. We will then compare this to
  the alternative, based on Kropotkin's work, of mutual aid and voluntary cooperation.

  I also want to highlight, maybe in a footnote, that AFAWK Darwin
  wasn't wrong, but social darwinism was.

* Writing notes

* Data

I spoke to some volunteers that I reached out to via WhatsApp. I
wanted to understand the motivations of the volunteers around me.

I did this through a conversational style. I kind of had a few
questions written down to guide me, but I didn't follow it like a
script. I let each conversation unfold, and that led me to interesting
places.

Most people I spoke to volunteered at their church, but for a lot of
them that wasn't the only place they had volunteered or done
charity. Some had done individual charity projects, some had joined
with existing organizations to do charity projects.

** Timi Spaine

Timi volunteered for something his church started called "Love
Feast". His grandma was part of the planners and he joined up to
assist her. He thinks that the experience was "quite nice", because he
would see people come in to get the food. This happened weekly, every Wednesday.

One of the other reasons he started to go was because of free food, a self-interest.

And then, later, he started to go there by himself, he had
internalized the activity and developed his own intrinsic motivations for doing this.

He says that the impact was more than 200 people.

But then he stopped after a while. And he thinks that what would make
him continue in his efforts again is "interest" and if he was an
integral part of the process.

He thinks that his efforts during his participation were not
"important". According to him, he only made the "sharing go faster".

Perhaps this signals that, even though there are altruistic reasons
for engaging in these activities, there still needs to be something
"in it" for the individual. The activities still need to challenge him, in a way.

According to him, being part of the planning process would make it
more "worthwhile, more worth my time. If it were just to share food, I
would still do it whenever I was available, but anybody could do that".

That's an interesting perspective. Concerning intrinsic and extrinsic
motivations, I wonder, if he was being paid to just "share food",
would he still consider the act to be "not worth his time"?

The answer to that question informs us as to how a more participatory
society can be built. If you want people to be self-motivated in the
repair and construction of their own communities, and you want to do
that with as little money as possible, then maybe you'd want to make
them a part of the process; make it more "worth their time"

** Iyinoluwa

Iyinoluwa also volunteers for his church, actually, many churches. Outside that he once
participated in a medical outreach program of which he did not
organize. He also just participated in the "sharing". They went to a
community to share medical drugs and equipment and did medical check-ups.

So, how did he get into the medical outreach thing? Well, his mum
dragged him along, and just like Timi. After doing it, he says he was "thrilled".

** Mercy Akinbusola

Mercy donated some money through her church to the less
privileged. She says that the experience made her happy to have seen
that she could feed someone "with the little resources that she had".

All of that seemed sort of run-of-the-mill to me, until she said the
other things she had done.

Mercy has given to orphans, twice.

Why? "I just wanted to put a smile on someone's face actually". She
stresses that it was self-directed; an agentic decision.

She even said that she would consider going more than once a week, if
she had enough resources.

When i prompted her on why she does this, she says:

"It's personal thing"
"I would be glad if our society can [provide for the less privileged more consistently]"
"I think our society can do more"

Which is interesting. She both proclaims it as a good for the
collective. The tension there is interesting.

Mercy wants people to join her in her efforts. She has convinced her sister to do so.

** Precious

Precious also volunteers in church and has participated outside the church several times.

For previous too, there's that family connection. Someone close to
her, her father, organizes the efforts and she participates. I wonder
if she would participate in such efforts if her father did not
organize them? I wonder if she would participate more if she was part of the organizing process.

* Notes

Some people started volunteering because of a family member, and then
once they do that, they see the efforts and internalize its values.

I think that this "internalize its values" is an important to think about.

* Questions generated

- Do these actions count as altruism? What really is altruism?
- How is activism different from altruism?  
- Is altruism contagious? Many people got to this through a family member, 
- Why does taking time and money out of their lives to help another
  person, whom they do not know, make them happy?
- I wonder, do these people donate to foundations that claim to
  address the very needs that they claim to care about? If not, then
  why not? My theory would be that they actually want to feel like
  they are a part of the solution, not just to pay away the guilt.
- Does mutual aid count as altruism?
- Do you have to put another person ahead of yourself to be
  altruistic? What if you helped them just as you help yourself?
